name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! 5"
      - name: Now it is
        run: date
      - name: Dir content
        run: ls -la
