name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: secrets
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: echo "$SECRETS"
      - name: variables
        env:
          VARIABLES: ${{ toJson(vars) }}
        run: echo "$VARIABLES"
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
